Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
    manager.vm.network "forwarded_port", guest: 8081, host: 9081
    manager.vm.network "forwarded_port", guest: 8082, host: 9082
    manager.vm.network "forwarded_port", guest: 8083, host: 9083
    manager.vm.network "forwarded_port", guest: 8084, host: 9084
    manager.vm.network "forwarded_port", guest: 8085, host: 9085
    manager.vm.network "forwarded_port", guest: 8086, host: 9086
    manager.vm.network "forwarded_port", guest: 8087, host: 9087
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end

  config.vm.define "node01" do |node01|
    node01.vm.hostname = "node01"
    node01.vm.network "private_network", ip: "192.168.56.11"
    node01.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    (8081..8087).each do |port|
      node01.vm.network "forwarded_port", guest: port, host: port
    end
    node01.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end

  config.vm.define "node02" do |node02|
    node02.vm.hostname = "node02"
    node02.vm.network "private_network", ip: "192.168.56.12"
    node02.vm.network "forwarded_port", guest: 22, host: 2224, id: "ssh"
    node02.vm.network "forwarded_port", guest: 80, host: 8088, id: "apache"
    node02.vm.network "forwarded_port", guest: 5432, host: 15432, id: "postgres"
    node02.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
  end
end
